#!/usr/bin/awk -f

function mkverts(vstr) {
	verts = ""
	split(vstr, vcha, "")
	verts = verts "v[" vcha[1] "], v[" vcha[2] "], v[" vcha[3] "], v[" \
		vcha[4] "]"
	return verts
}

BEGIN {
	print "def drawprfarrow(expr o)(suffix v, c) ="
}

{
	print "prfarrow(c, o, " $1 ", \"" $2 "\", " mkverts($3) ");"
}

END {
	print "enddef;"
}
